namabarang = input ("Masukan nama barang : ")
hargabarang = int (input ("Masukan harga barang :") )
nama_barang = input ("Masukan nama barang : ")
harga_barang = int (input ("Masukan harga barang :") )
_namabarang = input ("Masukan nama barang : ")
_hargabarang = int (input ("Masukan harga barang :") )

a = 10
persen = (a/100)
print ("\n")

print ("Nama barang =",namabarang)
keuntungan = int (hargabarang * persen)
print ("Harga barang =", hargabarang)
print ("Keuntungan = ", keuntungan)
hargajual = int (hargabarang + keuntungan)
print ( namabarang, "Dijual dengan harga Rp.", hargajual )
print ("\n")

print ("Nama barang =",nama_barang)
keuntungan1 = int (harga_barang * persen)
print ("Harga barang =", harga_barang)
print ("Keuntungan = ", keuntungan1)
hargajual1 = int(harga_barang + keuntungan1)
print ( nama_barang, "Dijual dengan harga Rp.", hargajual1 )
print ("\n")

print ("Nama barang =", _namabarang)
keuntungan2 = int ( _hargabarang * persen)
print ("Harga barang =", _hargabarang)
print ("Keuntungan = ", keuntungan2)
hargajual2 = int (_hargabarang + keuntungan2)
print ( _namabarang, "Dijual dengan harga Rp.", hargajual2 )
print ("\n")
